name: ROS2 CI

on:
  # Triggered whenever push to the master branch
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test
    # Create a container of the latest Ubuntu, other values could be
    # ubuntu-latest, ubuntu-22.04, etc.
    runs-on: ubuntu-20.04
    steps:
      # Install some system pacakges
      - name: Install ROS 2 Foxy packages
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update && sudo apt install -y curl
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install -y ros-foxy-ros-base python3-colcon-common-extensions
          sudo apt install -y lcov

      - name: Setup Workspace
        run: |
          source /opt/ros/foxy/setup.bash
          mkdir -p ros_ws/src/ros2_seminar_examples
          cd ros_ws
          colcon build
          source install/setup.bash
      
      # We want to use GitHub CI checkout version4 for checking out the branch
      # for Github Actions
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          path: ros_ws/src/ros2_seminar_examples

      # Build for test coverage
      - name: Configure CMake flags and build exectables
        run: |
          source /opt/ros/foxy/setup.bash
          sudo apt install python3-rosdep
          sudo rosdep init
          rosdep update --include-eol-distros
          cd ros_ws
          rosdep install --from-paths src -y --ignore-src
          colcon build --packages-select msg_srv_action_interface_example 
          colcon build

